### ISSUE TITLE
webui usage "billable only" does not apply for volumes

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamWebUI#276]
at least for Exoscale, VMs which are stopped are not billed, BUT their volumes still are...so in fact, in the webui GBh should not be affected by the billable toggle

**Comment by loomis** [comment]
The current UI implementation could be adapted to allow for the usage statistics to be correct for disk and the other metrics by performing two queries for each request: one with the billable flag enabled and one without.  The results of those two queries could then be merged.

However, the UI cannot be adapted to calculate the correct price in this case because of limitations of the server-side implementation.  In particular, the price (really cost) included in the metering records are always the full cost of the machine.  In the case of suspended machines, this cost is inflated because only the cost of the disk space should be included. 

Given that a correct solution requires some fundamental changes in the server-side implementation and that the current values are generally within ±10%, workarounds on the UI won't be implemented. An issue will be opened to discuss the changes necessary in the server-side implementation.
